name: Generate F1 Silverstone SVG

on:
  schedule:
    - cron: "0 1 * * *"  # runs daily at 01:00 UTC
  workflow_dispatch:

jobs:
  build_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Generate Silverstone F1 SVG
        run: |
          echo '<?xml version="1.0" encoding="UTF-8" standalone="no"?>' > output/github-f1.svg
          echo '<svg width="980" height="220" viewBox="0 0 980 220" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">' >> output/github-f1.svg
          echo '  <defs>' >> output/github-f1.svg
          echo '    <filter id="glow" x="-50%" y="-50%" width="200%" height="200%">' >> output/github-f1.svg
          echo '      <feGaussianBlur stdDeviation="6" result="coloredBlur"/>' >> output/github-f1.svg
          echo '      <feMerge><feMergeNode in="coloredBlur"/><feMergeNode in="SourceGraphic"/></feMerge>' >> output/github-f1.svg
          echo '    </filter>' >> output/github-f1.svg
          echo '    <g id="ferrariCar"><rect x="-10" y="-6" rx="3" ry="3" width="20" height="12" fill="#e10600"/><rect x="-7" y="-10" width="14" height="4" fill="#111" opacity="0.15"/><circle cx="-6" cy="8" r="2" fill="#111"/><circle cx="6" cy="8" r="2" fill="#111"/></g>' >> output/github-f1.svg
          echo '    <path id="trackPath" d="M80,110 C140,30 300,30 360,110 C410,180 560,180 620,110 C680,40 820,40 900,110 C840,150 720,150 660,120 C620,110 520,120 480,80 C440,40 300,40 240,80 C180,120 120,120 80,110 Z" fill="none" stroke="none"/>' >> output/github-f1.svg
          echo '  </defs>' >> output/github-f1.svg
          echo '  <rect width="100%" height="100%" fill="transparent"/>' >> output/github-f1.svg
          echo '  <path d="M80,110 C140,30 300,30 360,110 C410,180 560,180 620,110 C680,40 820,40 900,110 C840,150 720,150 660,120 C620,110 520,120 480,80 C440,40 300,40 240,80 C180,120 120,120 80,110 Z" fill="none" stroke="#1f2a30" stroke-width="22" stroke-linecap="round" stroke-linejoin="round" opacity="0.95"/>' >> output/github-f1.svg
          echo '  <use xlink:href="#trackPath" stroke="#ff6b6b" stroke-width="8" stroke-linecap="round" stroke-linejoin="round" opacity="0.55" filter="url(#glow)"/>' >> output/github-f1.svg
          echo '  <use xlink:href="#trackPath" stroke="#ffb4b4" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" opacity="0.8">' >> output/github-f1.svg
          echo '    <animate attributeName="stroke-dasharray" dur="6s" repeatCount="indefinite" values="1 1200;800 400;1 1200"/>' >> output/github-f1.svg
          echo '    <animate attributeName="stroke-dashoffset" dur="6s" repeatCount="indefinite" values="0;-1200;0"/>' >> output/github-f1.svg
          echo '  </use>' >> output/github-f1.svg
          echo '  <g filter="url(#glow)">' >> output/github-f1.svg
          echo '    <g id="movingCar"><use xlink:href="#ferrariCar"/><animateTransform attributeName="transform" type="rotate" values="0;6;-6;4;-4;0" dur="1.8s" repeatCount="indefinite"/></g>' >> output/github-f1.svg
          echo '    <animateMotion xlink:href="#movingCar" dur="6s" repeatCount="indefinite" rotate="auto"><mpath xlink:href="#trackPath"/></animateMotion>' >> output/github-f1.svg
          echo '  </g>' >> output/github-f1.svg
          echo '  <text x="50%" y="95%" text-anchor="middle" font-family="JetBrains Mono, monospace" font-size="16" fill="#cfefff" opacity="0.9">🏁 Hrithik Tej — The Developer'"'"'s Circuit</text>' >> output/github-f1.svg
          echo '</svg>' >> output/github-f1.svg

      - name: Commit SVG
        uses: EndBug/add-and-commit@v9
        with:
          add: "output/github-f1.svg"
          message: "🏁 update: generated Silverstone F1 circuit SVG"
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
